In [13]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import re  #regular expressions

In [2]:
df=pd.read_csv('train.csv')

In [3]:
df.head(5)

,id,qid1,qid2,question1,question2,is_duplicate
0,0,1,2,What is the step by step guide to invest in sh...,What is the step by step guide to invest in sh...,0
1,1,3,4,What is the story of Kohinoor (Koh-i-Noor) Dia...,What would happen if the Indian government sto...,0
2,2,5,6,How can I increase the speed of my internet co...,How can Internet speed be increased by hacking...,0
3,3,7,8,Why am I mentally very lonely? How can I solve...,Find the remainder when [math]23^{24}[/math] i...,0
4,4,9,10,"Which one dissolve in water quikly sugar, salt...",Which fish would survive in salt water?,0

In [4]:
#Lowercasing

In [7]:
df['question1']=df['question1'].str.lower()

In [8]:
df['question2']=df['question2'].str.lower()

In [9]:
df.head()

,id,qid1,qid2,question1,question2,is_duplicate
0,0,1,2,what is the step by step guide to invest in sh...,what is the step by step guide to invest in sh...,0
1,1,3,4,what is the story of kohinoor (koh-i-noor) dia...,what would happen if the indian government sto...,0
2,2,5,6,how can i increase the speed of my internet co...,how can internet speed be increased by hacking...,0
3,3,7,8,why am i mentally very lonely? how can i solve...,find the remainder when [math]23^{24}[/math] i...,0
4,4,9,10,"which one dissolve in water quikly sugar, salt...",which fish would survive in salt water?,0

In [10]:
#Removing HTML tags

In [20]:
def remove_html_tags(text):
    pattern = re.compile('<.*?>')              #regular expression to find HTML tags = <.*?>
    return pattern.sub(r'', str(text))

In [21]:
df['question1']=df['question1'].apply(remove_html_tags)

In [22]:
df['question2']=df['question2'].apply(remove_html_tags)

In [26]:
#Removing URLS

In [23]:
def remove_url(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'', str(text))

In [24]:
df['question1']=df['question1'].apply(remove_url)

In [25]:
df['question2']=df['question2'].apply(remove_url)

In [27]:
#Removing punctuations

In [28]:
import string

In [29]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [30]:
exclude = string.punctuation

In [31]:
def remove_punc(text):
    for char in exclude:
        text = text.replace(char,'')
    return text

In [32]:
df['question1']=df['question1'].apply(remove_punc)

In [33]:
df['question2']=df['question2'].apply(remove_punc)

In [35]:
df

,id,qid1,qid2,question1,question2,is_duplicate
0,0,1,2,what is the step by step guide to invest in sh...,what is the step by step guide to invest in sh...,0
1,1,3,4,what is the story of kohinoor kohinoor diamond,what would happen if the indian government sto...,0
2,2,5,6,how can i increase the speed of my internet co...,how can internet speed be increased by hacking...,0
3,3,7,8,why am i mentally very lonely how can i solve it,find the remainder when math2324math is divide...,0
4,4,9,10,which one dissolve in water quikly sugar salt ...,which fish would survive in salt water,0
...,...,...,...,...,...,...
404285,404285,433578,379845,how many keywords are there in the racket prog...,how many keywords are there in perl programmin...,0
404286,404286,18840,155606,do you believe there is life after death,is it true that there is life after death,1
404287,404287,537928,537929,what is one coin,whats this coin,0
404288,404288,537930,537931,what is the approx annual cost of living while...,i am having little hairfall problem but i want...,0
404289,404289,537932,537933,what is like to have sex with cousin,what is it like to have sex with your cousin,0

In [65]:
#saving
df.to_csv('v_basic_PP.csv', index=False)

In [39]:
#Spelling check

In [40]:
!pip install textblob

Collecting textblob
  Downloading textblob-0.17.1-py2.py3-none-any.whl (636 kB)
     ------------------------------------ 636.8/636.8 kB 269.1 kB/s eta 0:00:00
Collecting nltk>=3.1
  Downloading nltk-3.8.1-py3-none-any.whl (1.5 MB)
     ---------------------------------------- 1.5/1.5 MB 521.9 kB/s eta 0:00:00
Collecting regex>=2021.8.3
  Downloading regex-2023.6.3-cp310-cp310-win_amd64.whl (268 kB)
     -------------------------------------- 268.0/268.0 kB 2.7 MB/s eta 0:00:00
Requirement already satisfied: tqdm in c:\users\hrith\appdata\local\programs\python\python310\lib\site-packages (from nltk>=3.1->textblob) (4.65.0)
Requirement already satisfied: click in c:\users\hrith\appdata\local\programs\python\python310\lib\site-packages (from nltk>=3.1->textblob) (8.1.3)
Requirement already satisfied: joblib in c:\users\hrith\appdata\local\programs\python\python310\lib\site-packages (from nltk>=3.1->textblob) (1.2.0)
Requirement already satisfied: colorama in c:\users\hrith\appdata\local\programs\python\python310\lib\site-packages (from click->nltk>=3.1->textblob) (0.4.4)
Installing collected packages: regex, nltk, textblob
Successfully installed nltk-3.8.1 regex-2023.6.3 textblob-0.17.1

[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [41]:
from textblob import TextBlob

C:\Users\hrith\AppData\Local\Programs\Python\Python310\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.25.0
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [50]:

for i in range (len(df['question1'])):
    textblb1 = TextBlob(df['question1'][i])
    df['question1'][i] =textblb1.correct().string
    textblb2 = TextBlob(df['question2'][i])
    df['question2'][i] =textblb2.correct().string

C:\Users\hrith\AppData\Local\Temp\ipykernel_24480\1238339593.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['question1'][i] =textblb1.correct().string
C:\Users\hrith\AppData\Local\Temp\ipykernel_24480\1238339593.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['question2'][i] =textblb2.correct().string

KeyboardInterrupt:

In [51]:
#Removing stop words

In [55]:
import nltk

In [56]:
from nltk.corpus import stopwords

In [77]:
sw_=['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each',
 'few',
 'more',
 'most',
 'other',
 'some',
 'such',
 'no',
 'nor',
 'not',
 'only',
 'own',
 'same',
 'so',
 'than',
 'too',
 'very',
 's',
 't',
 'can',
 'will',
 'just',
 'don',
 "don't",
 'should',
 "should've",
 'now',
 'd',
 'll',
 'm',
 'o',
 're',
 've',
 'y',
 'ain',
 'aren',
 "aren't",
 'couldn',
 "couldn't",
 'didn',
 "didn't",
 'doesn',
 "doesn't",
 'hadn',
 "hadn't",
 'hasn',
 "hasn't",
 'haven',
 "haven't",
 'isn',
 "isn't",
 'ma',
 'mightn',
 "mightn't",
 'mustn',
 "mustn't",
 'needn',
 "needn't",
 'shan',
 "shan't",
 'shouldn',
 "shouldn't",
 'wasn',
 "wasn't",
 'weren',
 "weren't",
 'won',
 "won't",
 'wouldn',
 "wouldn't"]

In [78]:
sw_

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each',
 'few',
 'more',
 'most',
 'other',
 'some',
 'such',
 'no',
 'nor',
 'not',
 'only',
 'own',
 'same',
 'so',
 'than',
 'too',
 'very',
 's',
 't',
 'can',
 'will',
 'just',
 'don',
 "don't",
 'should',
 "should've",
 'now',
 'd',
 'll',
 'm',
 'o',
 're',
 've',
 'y',
 'ain',
 'aren',
 "aren't",
 'couldn',
 "couldn't",
 'didn',
 "didn't",
 'doesn',
 "doesn't",
 'hadn',
 "hadn't",
 'hasn',
 "hasn't",
 'haven',
 "haven't",
 'isn',
 "isn't",
 'ma',
 'mightn',
 "mightn't",
 'mustn',
 "mustn't",
 'needn',
 "needn't",
 'shan',
 "shan't",
 'shouldn',
 "shouldn't",
 'wasn',
 "wasn't",
 'weren',
 "weren't",
 'won',
 "won't",
 'wouldn',
 "wouldn't"]

In [79]:
def remove_stopwords(text):
    new_text = []
    
    for word in text.split():
        if word in sw_:
            new_text.append('')
        else:
            new_text.append(word)
    x = new_text[:]
    new_text.clear()
    return " ".join(x)

In [80]:
df['question2']=df['question2'].apply(remove_stopwords)

In [81]:
df['question1']=df['question1'].apply(remove_stopwords)

In [82]:
df.head(5)

,id,qid1,qid2,question1,question2,is_duplicate
0,0,1,2,step step guide invest share market india,step step guide invest share market,0
1,1,3,4,story kohinoor kohinoor diamond,would happen indian government stole kohin...,0
2,2,5,6,increase speed internet connection usin...,internet speed increased hacking des,0
3,3,7,8,mentally lonely solve,find remainder math2324math divided 2423,0
4,4,9,10,one dissolve water quickly sugar salt method...,fish would survive salt water,0

In [83]:
df.to_csv('v_basic_C.csv', index=False)

In [84]:
df_=pd.read_csv('v_basic_C.csv')

In [85]:
df_.head(5)

,id,qid1,qid2,question1,question2,is_duplicate
0,0,1,2,step step guide invest share market india,step step guide invest share market,0
1,1,3,4,story kohinoor kohinoor diamond,would happen indian government stole kohin...,0
2,2,5,6,increase speed internet connection usin...,internet speed increased hacking des,0
3,3,7,8,mentally lonely solve,find remainder math2324math divided 2423,0
4,4,9,10,one dissolve water quickly sugar salt method...,fish would survive salt water,0